# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Include dynamic layers whose content we need to append
#   - https://docs.yoctoproject.org/ref-manual/variables.html#term-BBFILES_DYNAMIC
BBFILES_DYNAMIC += " \
    swupdate:${LAYERDIR}/dynamic-layers/swupdate/*.bb \
    swupdate:${LAYERDIR}/dynamic-layers/swupdate/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-xilica-tr-sys"
BBFILE_PATTERN_meta-xilica-tr-sys = "^${LAYERDIR}/"
# bsp layer is 9, and we need to override recipes within
BBFILE_PRIORITY_meta-xilica-tr-sys = "10"

LAYERDEPENDS_meta-xilica-tr-sys = "variscite-bsp variscite-sdk swupdate"
LAYERSERIES_COMPAT_meta-xilica-tr-sys = "mickledore scarthgap"
